name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the observed behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Include a minimal repro if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: OS, Python version, plutus version, and install method.
    validations:
      required: true
