name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What limitation are you hitting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What API or behavior would help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: false
